theme: jekyll-theme-minimal
title: Anwar Khaddaj
description: >
  <img align="center" width="325" height="300" src="Anwar_Khaddaj_Picture.jpg">
  <br><br>
  <p style="text-align:center;">
    PhD student in Applied Mathematics<br>
    Co-Managing Director of Nucleate AZ<br>
    Communication Coach and Entrepreneur 
  </p>

